version: '3.7'

services:
  frontend:
    build: frontend
    volumes:
      - './frontend/:/app'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
  db:
    image: postgres
  web:
    build: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/code
    ports:
      - "8000:8000"
    depends_on:
      - db