# Generated by Django 2.2.3 on 2020-09-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itunes_id', models.IntegerField()),
                ('url', models.URLField(max_length=500)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itunes_id', models.IntegerField()),
                ('url', models.URLField(max_length=500)),
                ('artist_name', models.CharField(max_length=120)),
                ('release_date', models.DateField()),
                ('name', models.CharField(max_length=120)),
                ('artwork_url', models.URLField(max_length=500)),
                ('genres', models.ManyToManyField(to='podcast_player.Genre')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
